<?php
/**
 * AK Menu System — Update exclusion list.
 *
 * Returns an array of path patterns (relative to the application ROOT_PATH)
 * that the auto-update pipeline must NEVER overwrite or delete while copying
 * new release files over the existing install.
 *
 * These protect installation-specific data and user content:
 *   - config/db.php          → DB credentials generated by the installer
 *   - config/installed.lock  → install marker (its presence gates the app)
 *   - uploads/*              → tenant logos, menu images, QR codes
 *   - backups/*             → database + file backups
 *   - temp/*                → scratch space used by the updater itself
 *   - assets/cache/*        → generated cache (regenerated automatically)
 *   - templates/custom/*    → customer-authored custom menu templates
 *
 * NOTE: config/config.php IS intentionally allowed to update (it ships app
 * logic and constants). Only config/db.php + installed.lock are protected.
 *
 * Matching is done by the updater with a prefix/glob comparison on the
 * destination-relative path (see api/update.php → ak_is_excluded()).
 *
 * @return string[] list of relative paths / directory prefixes to skip
 */
return [
    'config/db.php',
    'config/installed.lock',
    'uploads',
    'backups',
    'temp',
    'assets/cache',
    'templates/custom',
];
